### ISSUE TITLE
not working with my video

### ISSUE THREAD

**Issue by alqasmi** [kemfic/Curved-Lane-Lines#1]
### can anyone help me, please see the picture:
I tried different videos but i got output video with totally wrong lane detection.

![screenshot 2019-01-01_github](https://user-images.githubusercontent.com/34480949/50571540-adad1d00-0dc6-11e9-9bc2-59f69d13afd3.jpg)

**Comment by kemfic** [comment]
Try messing around with the Sobel filter thresholds. If that doesn't work, change the ROI
